version: '3.8'

services:
  # Dashboard Web Frontend
  puertocho-web-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puertocho-web-dashboard
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # URL del backend del asistente (ajustar según tu configuración)
      - VITE_BACKEND_URL=http://localhost:8000
      - VITE_WEBSOCKET_URL=ws://localhost:8000/ws
    networks:
      - puertocho-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Servicio de desarrollo (comentado por defecto)
  # Descomenta para desarrollo local
  # puertocho-web-dev:
  #   image: node:20-alpine
  #   container_name: puertocho-web-dev
  #   working_dir: /app
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: npm run dev -- --host 0.0.0.0 --port 3000
  #   environment:
  #     - NODE_ENV=development
  #     - VITE_BACKEND_URL=http://localhost:8000
  #     - VITE_WEBSOCKET_URL=ws://localhost:8000/ws
  #   networks:
  #     - puertocho-network

networks:
  puertocho-network:
    driver: bridge
    name: puertocho-assistant-network
