# 🧠 Configuración COMPLETA del Modelo "Puertocho"
# Dataset: 503 positivos + 5000 negativos (Production Ready)

model:
  name: "puertocho_full"
  architecture: "mel_stft_1d_cnn"
  sample_rate: 16000
  frame_length: 1280
  num_mel_features: 32
  num_classes: 1

training:
  batch_size: 8
  learning_rate: 1e-4
  epochs: 50
  early_stopping_patience: 10
  validation_split: 0.2
  models_dir: "full_models"
  logs_dir: "full_logs"
  save_every_n_epochs: 5
  save_best_only: true

data:
  base_dir: "data"
  positive_dir: "data/all_train_samples"
  negative_dir: "data/negative"
  max_positive_samples: 503
  max_negative_samples: 5000
  target_fpr: 0.5
  target_fnr: 0.05
  normalize_audio: true
  apply_augmentation: false

optimization:
  optimizer: "adamw"
  weight_decay: 0.01
  use_amp: true
  gradient_clip_norm: 1.0
  scheduler: "onecycle"
  warmup_steps: 100
  loss_function: "bce_with_logits"

validation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
  classification_threshold: 0.5
  validate_every_n_epochs: 1

logging:
  level: "INFO"
  use_tensorboard: false
  use_wandb: false
  log_every_n_steps: 20

hardware:
  gpu_memory_fraction: 0.8
  allow_growth: true
  num_workers: 4
  pin_memory: true

reproducibility:
  seed: 42
  deterministic: false
  benchmark: true

openwakeword:
  model_architecture:
    type: "1d_cnn"
    num_layers: 4
    hidden_size: 128
    dropout: 0.3
  input_features:
    type: "mel_spectrogram"
    n_mels: 32
    hop_length: 320
    win_length: 640
  postprocessing:
    smoothing_window: 5
    threshold_adjustment: 0.0

export:
  export_onnx: true
  onnx_opset: 11
  onnx_dynamic_axes: true
  onnx_optimize: true
  onnx_fp16: false

testing:
  test_split: 0.1
  final_evaluation_metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "confusion_matrix" 