services:
  puertocho-assistant:
    build: .
    container_name: puertocho-assistant
    privileged: true
    network_mode: host
    devices:
      - "/dev/snd:/dev/snd"
      - "/dev/gpiomem:/dev/gpiomem"
    restart: unless-stopped
    environment:
      - TRANSCRIPTION_SERVICE_URL=${TRANSCRIPTION_SERVICE_URL:-http://localhost:5000/transcribe}
      - BUTTON_PIN=${BUTTON_PIN:-22}
      - LED_IDLE_PIN=${LED_IDLE_PIN:-17}
      - LED_RECORD_PIN=${LED_RECORD_PIN:-27}
      - OPENWAKEWORD_MODEL_PATHS=${OPENWAKEWORD_MODEL_PATHS:-}
      - OPENWAKEWORD_THRESHOLD=${OPENWAKEWORD_THRESHOLD:-0.5}
      - OPENWAKEWORD_VAD_THRESHOLD=${OPENWAKEWORD_VAD_THRESHOLD:-0.0}
      - OPENWAKEWORD_ENABLE_SPEEX_NS=${OPENWAKEWORD_ENABLE_SPEEX_NS:-false}
      - OPENWAKEWORD_INFERENCE_FRAMEWORK=${OPENWAKEWORD_INFERENCE_FRAMEWORK:-onnx}
      - AUDIO_SAMPLE_RATE=${AUDIO_SAMPLE_RATE:-16000}
      - AUDIO_CHANNELS=${AUDIO_CHANNELS:-1}
      - AUDIO_CHUNK_SIZE=${AUDIO_CHUNK_SIZE:-1280}
      - MODE=${MODE:-GPIO_ONLY}
      - PULSE_RUNTIME_PATH=/tmp/pulse
      - ALSA_CARD=0
    volumes:
      - "/dev:/dev"
      - "/sys:/sys"
      - "/tmp:/tmp"
      - "/run/user/1000/pulse:/tmp/pulse-socket"
