services:
  puertocho-assistant:
    build: .
    container_name: puertocho-assistant
    privileged: true
    network_mode: host
    devices:
      - "/dev/snd:/dev/snd"
      - "/dev/gpiomem:/dev/gpiomem"
    restart: unless-stopped
    environment:
      - PORCUPINE_ACCESS_KEY=${PORCUPINE_ACCESS_KEY}
      - TRANSCRIPTION_SERVICE_URL=${TRANSCRIPTION_SERVICE_URL:-http://localhost:5000/transcribe}
      - BUTTON_PIN=${BUTTON_PIN:-22}
      - LED_IDLE_PIN=${LED_IDLE_PIN:-17}
      - LED_RECORD_PIN=${LED_RECORD_PIN:-27}
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
      - AUDIO_DEVICE_INDEX=3
      - SDL_AUDIODRIVER=alsa
    volumes:
      - "/dev:/dev"
      - "/sys:/sys"
      - "/run/user/1000/pulse:/run/user/1000/pulse"
